### ISSUE TITLE
Example sketches?

### ISSUE THREAD

**Issue by dglaude** [pimoroni/espiot-phat#7]
On this [page](http://learn.pimoroni.com/tutorial/hal13/micropython-on-esp-iot-phat) @RogueM (?) wrote something about "uploading example sketches":

> (we'll be uploading example sketches for the above, as well as others, to the espiot-phat GitHub repo in the coming weeks so keep an eye up there if you are stuck).

What are supposed to contain those sketches???
Are those the how to connect and LED and an analog sensor for the example of that page to work?

I believe the issues might be:
1) Put the right resistor in front of the LED
2) Make a voltage divisor so that value on ADC is from 0V to 1V (I read that somewhere)

What else could go wrong?

**Comment by RogueM** [comment]
In that tutorial, I was merely referring to the ubiquitious 'blink' and a (slightly) more elaborate 'breathing LED' example, the suggested 'homework' closing the tutorial, from a coding point of view, but eventually the intention is to feature additional MicroPython scripts (and Arduino sketches) in this repo that can be transferred onto the chip.

This was planned as a tie-in of sorts with the next guide that was going to cover (among other things) file transfer of custom scripts, but right now this is a side of MicroPython still in its infancy and backward-incompatible changes are on the map from the webrepl side of things, so that installment in the series is on hold.

... still I'm working in my spare time on stuff I might decide to upload to the repo ahead of time if I feel there's a value, even if only for advanced users, though it's more likely to pop up on my fork prior to them showing up here.
